### PR TITLE
Add support for Python 2 and 3

### LINKED ISSUE #22: Python3 issues
Not-necessarily-exhaustive list of Python 3 issues:

* `urllib2` module is gone - is replaced by `urllib.request` and `urllib.error`
* `urlparse` module is renamed to `urllib.parse`
* `dict.iteritems` is gone, replaced by `items`. This exists in python 2, but with nonlazy semantics, not a breaking change to switch.
* `%` syntax for formatting strings is gone. Replace `'... %s ...' % x` with `'... {} ...'.format(x)` - Unfortunately this was added in 2.6, so this is a breaking change for 2.5
* Relative imports must be explicit. `from version import ...` changes to `from .version import ...`

### PR DESCRIPTION
**Pull request by saj**
Fixes #22.

Please note that this pull request will drop support for Python 2.5.

Tested with:
  - CPython 2.6.9
  - CPython 2.7.10
  - CPython 3.3.6
  - CPython 3.4.3

I was forced to add a handful of unit tests to ensure basic functionality across the different runtimes. These tests offer minimal coverage. Tests for paginated responses and writes are missing. The tests that do exist may differ from your house style.

### CODE REVIEW

**Comment by wbyoung** [comment]
:+1:

**Comment by gmjosack** [comment]
Thanks a lot for taking this on. Especially adding some basic unit tests.

Can you update the `.travis.yml` to run the new unit tests as well?

**Comment by saj** [comment]
> Can you update the .travis.yml to run the new unit tests as well?

Done.

Even with the new unit tests in c938946, the changes to the Travis configuration in e6b9d20 have halved CI build times:

https://travis-ci.org/dropbox/pygerduty/builds/84478461
https://travis-ci.org/dropbox/pygerduty/builds/84546353

You might want to check your other projects for the same problem.  More comprehensive (time consuming) test suites will amplify the negative effect.

Cheers.

**Comment by gmjosack** [comment]
Yeah, I'd noticed that problem as I asked you to add the tests. I don't normally use tox (that was another pull request) so thanks for fixing that up as well!

**Comment by gmjosack** [comment]
This has been pushed up to PyPI as `pygerduty-0.29.0`

Thanks again for the work here!

**Comment by wbyoung** [comment]
Thanks @saj and @chris-martin & for the quick release @gmjosack.

**Comment by chris-martin** [comment]
Thanks everybody :)

**Pull request merged**
