### PR TITLE
Adding Teams endpoint into the project

### PR DESCRIPTION
**Pull request by tkensiski**
Added the teams endpoints.

Docs are located here: https://developer.pagerduty.com/documentation/rest/teams

### CODE REVIEW

**Comment by gmjosack** [comment]
Can you put 2 new lines between top level classes per pep8 as well as bump the version? Thanks!

**Comment by tkensiski** [comment]
Hey @gmjosack can you merge this. I fixed what you asked for?

**Comment by gmjosack** [comment]
This was manually merged to resolve conflict and squash commits. I've pushed this up to PyPI. Sorry for the delay.

**Comment by tkensiski** [comment]
Awesome thanks

**Pull request closed without merging**
