### PR TITLE
Make the pagination limit configurable

### PR DESCRIPTION
**Pull request by marpetr**

### CODE REVIEW

**Comment by gmjosack** [comment]
There are often times I need to use `list` to query and stop short so I don't know that I'd want the max to be the default. Would you mind making this configurable in the constructor?

**Comment by marpetr** [comment]
I've made changes according to your suggestion.

By the way, the 'stop short' argument is valid only for very small datasets. During my tests, a request to /incidents/ endpoint with limit=25 on average took 1.0s, and with limit=100 it took 1.6s.

If you find what you're looking for in the first 25 items, you win 0.6 seconds. If you find it between the 26th and the 50th item, you lose 0.4s. If you iterate until the 1000th item, you could have saved 24 seconds. It gets worse as the list size increases. To sum up, I don't see a real use case for limit < 100.

**Comment by gmjosack** [comment]
Thanks for the contribution!

**Comment by gmjosack** [comment]
`pygerduty-0.31.0` has been pushed with your changes.

**Pull request merged**
