### PR TITLE
fix Services.enable() and Services.disable()

### PR DESCRIPTION
**Pull request by axinojolais**
As per https://v2.developer.pagerduty.com/v2/page/api-reference#!/Services/put_services_id - only tested with the v2 API.

### CODE REVIEW

**Comment by axinojolais** [comment]
travis CI build probably needs fixing, failure appears to be unrelated to my changes.

**Comment by cugini-dbx** [comment]
Hello, sorry for the delay, I just took over maintenance for this project. This change looks good to me. Would you mind rebasing with the latest changes which fixed the tox config?

**Comment by axinojolais** [comment]
@cugini-dbx done

**Comment by cugini-dbx** [comment]
Thanks!

**Pull request merged**
